# Generated by Django 2.2.19 on 2022-07-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220713_0853'),
        ('posts', '0003_auto_20220715_0843'),
    ]

    operations = [
    ]
